### ISSUE TITLE
Improve psudo openpose.

### ISSUE THREAD

**Issue by tomudo** [Fannovel16/ComfyUI-MotionDiff#14]
I use motion data visualizer node to generate openpose pictures but it could not use with openpose controlnet perfectly. I tried dwpose convertion but dwpose cannot recognize some poses. I request to improve psudo openpose to generate better openpose picture. Thank you.

**Comment by spelafort** [comment]
I'm having the same issue. The DWPose Estimator seems to randomly skips frames for no apparent reason. Does anyone have any tips on this?

**Comment by kijai** [comment]
> I'm having the same issue. The DWPose Estimator seems to randomly skips frames for no apparent reason. Does anyone have any tips on this?

With the latest updates, there's now options to change the character shape and render the view as normal map, which I find works really well with dwpose.

**Comment by Fannovel16** [comment]
You can use "Render OpenPose from SMPL Multiple" (only appliable to 4DHuman tho)
