### ISSUE TITLE
The first image is very slow to generate. 

### ISSUE THREAD

**Issue by toyxyz** [Fannovel16/ComfyUI-MotionDiff#23]
When I try to create an image with MotionDiff installed, it works very slowly. From the second time, it works fine again. 

MotionDiff installed
![image](https://github.com/Fannovel16/ComfyUI-MotionDiff/assets/8006000/7796c93d-8cf5-4883-a156-1ce9ef8cfdcb)

Without ModtionDiff
![image](https://github.com/Fannovel16/ComfyUI-MotionDiff/assets/8006000/adbed008-d169-4861-8292-74523f1118b5)

**Comment by Fannovel16** [comment]
Fixed in this commit: https://github.com/Fannovel16/ComfyUI-MotionDiff/pull/25
