### ISSUE TITLE
Possible to increase frame max?

### ISSUE THREAD

**Issue by spelafort** [Fannovel16/ComfyUI-MotionDiff#33]
Is it possible to change things so we can use 'empty motion data' larger than 196 frames?

It's quite limiting at the moment. I've tried manually changing the max but it throws an error.

**Comment by Fannovel16** [comment]
I'm afraid that's not possible. 196 frames limit is hardcoded in the original code as there is no motion sequence longer than 196 frames in HumanML3D motion database.
